name: Deploy
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'master' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
          source-url: https://apiint.nugettest.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
      - name: Build
        run: dotnet build Bandwidth.Standard
      - name: Pack
        run: dotnet pack --configuration Release Bandwidth.Standard
      - name: Push
        run: dotnet nuget push Bandwidth.Standard/bin/Release/*.nupkg
