name: Deploy
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - name: Build project
        run: dotnet build -c Bandwidth.Standard
      - name: Package project
        run: dotnet pack -c Release Bandwidth.Standard
      - name: Push package
        env:
          NUGET_SOURCE: https://apiint.nugettest.org/v3/index.json
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: dotnet nuget push Bandwidth.Standard/bin/Release/*.nupkg -s $SOURCE -k $NUGET_KEY
