name: Deploy
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - run: dotnet build Bandwidth.Standard
      - run: dotnet pack --configuration Release Bandwidth.Standard
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      - run: dotnet nuget push Bandwidth.Standard/bin/Release/*.nupkg -s https://apiint.nugettest.org/v3/index.json -k $NUGET_KEY
