name: Integrate
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get_collaborator_permission
        with:
          route: GET /repos/:owner/:repo/collaborators/:username/permission
          owner: Bandwidth
          repo: csharp-sdk
          username: ${{ github.event.release.author.login }}
      - run: echo "Permission - ${{ fromJson(steps.get_collaborator_permission.outputs.data).permission }}"